[workspace]
resolver = "2"
members = [
    "downloader-core",
    "downloader-cli",
    "launcher-gui/src-tauri"
, "manifest-cdn"]

[profile.release]
lto = true
codegen-units = 1
opt-level = "z"
panic = "abort"
