// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { RepositoryWithMeta } from './RepositoryWithMeta'

export type FolderWithMeta = {
    path: string
    isValid: boolean
    error: string | null
    repositories: Array<RepositoryWithMeta>
}
