// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonWithMeta } from './AddonWithMeta'

export type RepositoryWithMeta = {
    repoUrl: string
    repoName: string
    owner: string
    currentBranch: string | null
    availableBranches: Array<string>
    repoRef: string | null
    addons: Array<AddonWithMeta>
}
