// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Dlone'o not edit this file manually.

export type Addon = {
    name: string
    dir: string
    names: Array<string>
    isSymlinked: boolean
    notes: string | null
    customName: string | null
}
