// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addon } from './Addon'
import type { AddonSource } from './AddonSource'

export type AddonRepository = { source: AddonSource; addons: Array<Addon> }
