// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type AddonSource =
    | {
          type: 'git'
          repo_url: string
          owner: string
          repo_name: string
          current_branch: string | null
          available_branches: Array<string>
          repo_ref: string | null
          latest_ref: string | null
          readme: string | null
      }
    | { type: 'local'; folder_name: string; path: string }
