// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddOnsFolderUserMeta } from './AddOnsFolderUserMeta'

/**
 * user configuration stored in Tauri store
 */
export type AddOnsUserConfig = {
    /**
     * All managed AddOns directories and their metadata
     */
    folders: Array<AddOnsFolderUserMeta>
}
