// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonRepositoryUserMeta } from './AddonRepositoryUserMeta'

/**
 * User metadata for a single AddOns directory
 */
export type AddOnsFolderUserMeta = {
    /**
     * Absolute path to the AddOns directory
     */
    path: string
    repos: Array<AddonRepositoryUserMeta>
}
