// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Addon } from './Addon'

export type AddonRepository = {
    repoUrl: string
    repoName: string
    owner: string
    currentBranch: string | null
    availableBranches: Array<string>
    repoRef: string | null
    latestRef: string | null
    addons: Array<Addon>
}
