// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonUserMeta } from './AddonUserMeta'

export type AddonRepositoryUserMeta = {
    repoUrl: string
    addons: { [key in string]?: AddonUserMeta }
}
