// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AddonRepository } from './AddonRepository'

export type AddOnsFolder = {
    path: string
    isValid: boolean
    error: string | null
    repositories: Array<AddonRepository>
}
