// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationEvent } from './OperationEvent'
import type { OperationKey } from './OperationKey'

export type OperationEventPayload = { key: OperationKey; event: OperationEvent }
