// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { OperationType } from './OperationType'

export type OperationEvent =
    | { started: { operation: OperationType } }
    | { progress: { current: number; total: number } }
    | { status: string }
    | { warning: string }
    | { error: string }
    | 'completed'
