name: Build Manifest

on:
    pull_request:
        paths:
            - 'manifest-cdn/**'
            - 'downloader-core/**'
            - '.github/workflows/build-manifest.yml'
    push:
        branches: ['main']
        paths:
            - 'manifest-cdn/**'
            - 'downloader-core/**'
            - '.github/workflows/build-manifest.yml'

jobs:
    build-manifest:
        name: Build manifest-cdn
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: Install Rust stable
              uses: dtolnay/rust-toolchain@stable
            - name: Build manifest-cdn
              run: |
                  cd manifest-cdn
                  cargo build --locked --release
