name: Build Addon Manager GUI

on:
    pull_request:
        paths:
            - 'addon-manager-gui/src-tauri**'
            - 'downloader-core/**'
            - '.github/workflows/build-addon-manager-gui.yml'
    push:
        branches: ['main']
        paths:
            - 'addon-manager-gui/src-tauri**'
            - 'downloader-core/**'
            - '.github/workflows/build-addon-manager-gui.yml'

# This workflow will build your tauri app without uploading it anywhere.

concurrency:
    group: ${{ github.workflow }}-${{ github.ref }}
    cancel-in-progress: true

jobs:
    test-tauri-addon-manager-gui:
        runs-on: ubuntu-24.04
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
            - name: Install Bun
              uses: oven-sh/setup-bun@v2
            - name: install dependencies (ubuntu only)
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            - name: Install frontend dependencies
              run: |
                  cd addon-manager-gui
                  bun install
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  projectPath: addon-manager-gui
