name: Build CLI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          components: clippy, rustfmt
      - name: format
        run: |
          cargo fmt --version
          cargo fmt --all -- --check
      - name: lint
        run: |
          cargo clippy --version
          cargo clippy -- -D warnings
      - name: test
        run: cargo test --verbose

  build-cli-linux-windows:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          targets: x86_64-unknown-linux-gnu, x86_64-pc-windows-gnu
      - name: Prepare dist directory
        run: mkdir -p dist/cli
      - name: Copy LICENSE to dist
        run: cp LICENSE dist/
      - name: Build Linux
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-unknown-linux-gnu
          mv ../target/x86_64-unknown-linux-gnu/release/downloader-cli ../dist/cli/downloader-cli-linux-x86_64
      - name: Setup Windows - Install mingw-w64
        run: sudo apt-get install -y mingw-w64
      - name: Build Windows
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-pc-windows-gnu
          mv ../target/x86_64-pc-windows-gnu/release/downloader-cli.exe ../dist/cli/downloader-cli-windows-x86_64.exe
      - name: Upload CLI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-artifacts
          path: dist/cli/
          retention-days: 3

  build-cli-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          targets: x86_64-apple-darwin,aarch64-apple-darwin
      - name: Prepare dist directory
        run: mkdir -p dist/cli
      - name: Copy LICENSE to dist
        run: cp LICENSE dist/
      - name: Build macOS (Intel)
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-apple-darwin
          mv ../target/x86_64-apple-darwin/release/downloader-cli ../dist/cli/downloader-cli-macos-x86_64
      - name: Build macOS (Apple Silicon)
        run: |
          cd downloader-cli
          cargo build --locked --release --target aarch64-apple-darwin
          mv ../target/aarch64-apple-darwin/release/downloader-cli ../dist/cli/downloader-cli-macos-aarch64
      - name: Upload CLI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: cli-artifacts-macos
          path: dist/cli/
          retention-days: 3

  release:
    runs-on: ubuntu-24.04
    needs: [build-cli-linux-windows, build-cli-macos]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux and Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-artifacts
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: dist/cli/

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-artifacts-macos
          run-id: ${{ github.event.inputs.run_id }}
          github-token: ${{ secrets.GITHUB_TOKEN }}
          path: dist/cli/

      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: |
            dist/cli/downloader-cli-linux-x86_64
            dist/cli/downloader-cli-windows-x86_64.exe
            dist/cli/downloader-cli-macos-aarch64
            LICENSE
            README.md