name: Build CLI

on:
  push:
    branches: ['main']
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-cli-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: moonrepo/setup-rust@v1
        with:
          targets: x86_64-unknown-linux-gnu
      - name: Prepare dist directory
        run: mkdir -p dist/cli
      # - name: Copy LICENSE to dist
        # run: cp LICENSE dist/
      - name: Build Linux (Demo)
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-unknown-linux-gnu