name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'desired version'
        required: true
        default: 'v0.2.3'

jobs:
  build-cli-all-platforms:
    strategy:
      matrix:
        include:
          - platform: ubuntu-24.04
            target: x86_64-unknown-linux-gnu
            artifact-name: cli-artifacts
            setup-windows: true
          - platform: macos-latest
            target: x86_64-apple-darwin,aarch64-apple-darwin
            artifact-name: cli-artifacts-macos
            setup-windows: false
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
        with:
          targets: ${{ matrix.target }}${{ matrix.setup-windows && ',x86_64-pc-windows-gnu' || '' }}
      - name: Prepare dist directory
        run: mkdir -p dist/cli
      # - name: Copy LICENSE to dist
      #   run: cp LICENSE dist/

      # Linux builds (on Ubuntu runner)
      - name: Build Linux (Demo)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-unknown-linux-gnu
          mv ../target/x86_64-unknown-linux-gnu/release/downloader-cli ../dist/cli/downloader-cli-${{ github.event.inputs.version }}-linux-x86_64
      - name: Build Linux (Production)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          cd downloader-cli
          cargo build --features production --locked --release --target x86_64-unknown-linux-gnu --bin downloader-cli
          mv ../target/x86_64-unknown-linux-gnu/release/downloader-cli ../dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-linux-x86_64

      # Windows builds (on Ubuntu runner with cross-compilation)
      - name: Setup Windows - Install mingw-w64
        if: matrix.platform == 'ubuntu-24.04'
        run: sudo apt-get install -y mingw-w64
      - name: Build Windows (Demo)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-pc-windows-gnu
          mv ../target/x86_64-pc-windows-gnu/release/downloader-cli.exe ../dist/cli/downloader-cli-${{ github.event.inputs.version }}-windows-x86_64.exe

      - name: Build Windows (Production)
        if: matrix.platform == 'ubuntu-24.04'
        run: |
          cd downloader-cli
          cargo build --features production --locked --release --target x86_64-pc-windows-gnu --bin downloader-cli
          mv ../target/x86_64-pc-windows-gnu/release/downloader-cli.exe ../dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-windows-x86_64.exe

      # macOS builds (on macOS runner)
      - name: Build macOS (Intel, Demo)
        if: matrix.platform == 'macos-latest'
        run: |
          cd downloader-cli
          cargo build --locked --release --target x86_64-apple-darwin
          mv ../target/x86_64-apple-darwin/release/downloader-cli ../dist/cli/downloader-cli-${{ github.event.inputs.version }}-macos-x86_64
      - name: Build macOS (Intel, Production)
        if: matrix.platform == 'macos-latest'
        run: |
          cd downloader-cli
          cargo build --features production --locked --release --target x86_64-apple-darwin --bin downloader-cli
          mv ../target/x86_64-apple-darwin/release/downloader-cli ../dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-macos-x86_64
      - name: Build macOS (Apple Silicon, Demo)
        if: matrix.platform == 'macos-latest'
        run: |
          cd downloader-cli
          cargo build --locked --release --target aarch64-apple-darwin
          mv ../target/aarch64-apple-darwin/release/downloader-cli ../dist/cli/downloader-cli-${{ github.event.inputs.version }}-macos-aarch64
      - name: Build macOS (Apple Silicon, Production)
        if: matrix.platform == 'macos-latest'
        run: |
          cd downloader-cli
          cargo build --features production --locked --release --target aarch64-apple-darwin --bin downloader-cli
          mv ../target/aarch64-apple-darwin/release/downloader-cli ../dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-macos-aarch64
      - name: Upload CLI artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.artifact-name }}
          path: dist/cli/
          retention-days: 3

  publish-production:
    needs: build-cli-all-platforms
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux and Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-artifacts
          path: dist/cli/

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-artifacts-macos
          path: dist/cli/

      - name: Create Production Release
        id: create_production_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Project Epoch Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: false
          files: |
            dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-linux-x86_64
            dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-windows-x86_64.exe
            dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-macos-x86_64
            dist/cli/epoch_patcher-cli-${{ github.event.inputs.version }}-macos-aarch64
            LICENSE
            README.md

  publish-demo:
    needs: build-cli-all-platforms
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Linux and Windows Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-artifacts
          path: dist/cli/

      - name: Download macOS Artifacts
        uses: actions/download-artifact@v4
        with:
          name: cli-artifacts-macos
          path: dist/cli/

      - name: Create Demo Release
        id: create_demo_release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
        with:
          tag_name: ${{ github.event.inputs.version }}-demo
          name: Demo Launcher Release ${{ github.event.inputs.version }}
          draft: true
          prerelease: true
          files: |
            dist/cli/downloader-cli-${{ github.event.inputs.version }}-linux-x86_64
            dist/cli/downloader-cli-${{ github.event.inputs.version }}-windows-x86_64.exe
            dist/cli/downloader-cli-${{ github.event.inputs.version }}-macos-x86_64
            dist/cli/downloader-cli-${{ github.event.inputs.version }}-macos-aarch64
            LICENSE
            README.md

  publish-demo-tauri:
    needs: build-cli-all-platforms # only build the GUI once all CLI artifacts are ready
    permissions:
      contents: write
    strategy:
      fail-fast: false
      matrix:
        include:
          - platform: "macos-latest" # for Arm based macs (M1 and above).
            args: "--target aarch64-apple-darwin"
          - platform: "macos-latest" # for Intel based macs.
            args: "--target x86_64-apple-darwin"
          - platform: "ubuntu-22.04" # for Tauri v1 you could replace this with ubuntu-20.04.
            args: ""
          - platform: "windows-latest"
            args: ""
    runs-on: ${{ matrix.platform }}
    steps:
      - uses: actions/checkout@v4
      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
      - name: install Rust stable
        uses: dtolnay/rust-toolchain@stable
        with:
          # Those targets are only used on macos runners so it's in an `if` to slightly speed up windows and linux builds.
          targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
      - name: install dependencies (ubuntu only)
        if: matrix.platform == 'ubuntu-22.04' # This must match the platform value defined above.
        run: |
          sudo apt-get update
          sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
      - name: Install Bun
        uses: oven-sh/setup-bun@v2
      - name: Install frontend dependencies
        run: |
          cd launcher-gui
          bun install
      - uses: tauri-apps/tauri-action@v0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          projectPath: launcher-gui
          tagName: ${{ github.event.inputs.version }}-demo
          releaseName: "Demo Launcher GUI v${{ github.event.inputs.version }}"
          releaseBody: "Demo version - For testing purposes only. See the assets to download this version and install."
          releaseDraft: true
          prerelease: true
          args: ${{ matrix.args }}
