name: Release

on:
    workflow_dispatch:
        inputs:
            version:
                description: 'Desired version tag'
                required: true
                default: 'v0.2.7'

jobs:
    publish-rs-addon-manager:
        permissions:
            contents: write
        strategy:
            fail-fast: false
            matrix:
                include:
                    - platform: 'ubuntu-24.04'
                      args: ''
                    - platform: 'windows-latest'
                      args: ''
                    - platform: 'macos-latest'
                      args: '--target aarch64-apple-darwin'
        runs-on: ${{ matrix.platform }}
        steps:
            - uses: actions/checkout@v4
            - name: setup node
              uses: actions/setup-node@v4
              with:
                  node-version: lts/*
            - name: install Rust stable
              uses: dtolnay/rust-toolchain@stable
              with:
                  targets: ${{ matrix.platform == 'macos-latest' && 'aarch64-apple-darwin,x86_64-apple-darwin' || '' }}
            - name: install dependencies (ubuntu only)
              if: matrix.platform == 'ubuntu-24.04'
              run: |
                  sudo apt-get update
                  sudo apt-get install -y libwebkit2gtk-4.1-dev libappindicator3-dev librsvg2-dev patchelf
            - name: Install Bun
              uses: oven-sh/setup-bun@v2
            - name: Install frontend dependencies
              run: |
                  cd addon-manager-gui
                  bun install
            - uses: tauri-apps/tauri-action@v0
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  projectPath: addon-manager-gui
                  tagName: ${{ github.event.inputs.version }}
                  releaseName: 'Addon Manager v${{ github.event.inputs.version }}'
                  releaseBody: 'Production release of the Addon Manager application.'
                  releaseDraft: true
                  prerelease: false
                  args: ${{ matrix.args }}
